/* scripts/build-sprites.cjs — embed the character pose PNGs as data-URIs.
   Reads assets/atlas-poses/*.png (the team's approved character artwork) and emits
   lib/atlas-sprites.js. Data-URIs keep the game fully self-contained: no external
   requests, no hosting, no CSP changes — the single-file POC property holds.
   Run:  node scripts/build-sprites.cjs                                        */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const srcDir = path.join(root, 'assets', 'atlas-poses');

// file -> sprite key (the engine's vocabulary)
const MAP = {
  '01_front.png': 'front',
  '02_three_quarter.png': 'threeq',
  '03_side_profile.png': 'profile',
  '04_back.png': 'back',
  '05_back_turned.png': 'backthreeq',
  '06_face_neutral_smile.png': 'face_neutral',
  '07_face_happy.png': 'face_talk',
  '08_face_surprised.png': 'face_surprised',
  '09_face_sad.png': 'face_sad',
  '10_face_angry.png': 'face_angry',
  '11_face_wink.png': 'face_wink',
  '12_face_laughing.png': 'face_joy',
  '13_walking.png': 'walk',
  '14_running.png': 'run',
  '15_waving.png': 'wave',
  '16_pointing.png': 'point',
  '17_thinking.png': 'think',
  '18_sitting.png': 'sit',
};

const metrics = JSON.parse(fs.readFileSync(path.join(root, 'assets', 'sprite-metrics.json'), 'utf8'));

const out = {};
let total = 0;
for (const [file, key] of Object.entries(MAP)) {
  const p = path.join(srcDir, file);
  if (!fs.existsSync(p)) { console.warn('MISSING:', file, '→', key); continue; }
  const buf = fs.readFileSync(p);
  const w = buf.readUInt32BE(16), h = buf.readUInt32BE(20);
  const m = metrics[file] || null;   // bbox + head measurements from analyze-sprites.cjs
  out[key] = { src: 'data:image/png;base64,' + buf.toString('base64'), w, h, m };
  total += buf.length;
}

const body =
  '/* lib/atlas-sprites.js — GENERATED by scripts/build-sprites.cjs. Do not edit.\n' +
  '   The team-approved Orion character artwork, embedded as data-URIs so the\n' +
  '   game stays fully self-contained (no external requests). */\n' +
  'export const ATLAS_SPRITES = ' + JSON.stringify(out) + ';\n';
fs.writeFileSync(path.join(root, 'lib', 'atlas-sprites.js'), body);
console.log('wrote lib/atlas-sprites.js —', Object.keys(out).length, 'sprites,',
  (total / 1024).toFixed(0) + ' KB raw,', (body.length / 1024).toFixed(0) + ' KB module');
